# Generated by Django 2.2.6 on 2020-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwmovies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongzuopian',
            name='movie_star',
            field=models.CharField(max_length=30),
        ),
    ]
