# Generated by Django 2.2.6 on 2020-07-17 14:03

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='htmlbody',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
